using Npgsql;
using NpgsqlTypes;
using Taskflow.Models;

namespace Taskflow.Data;

public sealed class TaskStore
{
    private readonly string _connectionString;

    public TaskStore(IConfiguration configuration)
    {
        var databaseUrl = configuration["DATABASE_URL"]
            ?? configuration["POSTGRES_URL"];

        if (string.IsNullOrWhiteSpace(databaseUrl))
            throw new InvalidOperationException("Set DATABASE_URL to your hosted PostgreSQL connection string.");

        _connectionString = BuildConnectionString(databaseUrl);
    }

    private static NpgsqlConnection Connect(string connectionString) => new(connectionString);

    internal static string BuildConnectionString(string value)
    {
        if (!Uri.TryCreate(value, UriKind.Absolute, out var uri) ||
            (uri.Scheme != "postgres" && uri.Scheme != "postgresql"))
            return value;

        var userInfo = uri.UserInfo.Split(':', 2);
        var builder = new NpgsqlConnectionStringBuilder
        {
            Host = uri.Host,
            Port = uri.IsDefaultPort ? 5432 : uri.Port,
            Database = Uri.UnescapeDataString(uri.AbsolutePath.TrimStart('/')),
            Username = Uri.UnescapeDataString(userInfo[0]),
            Password = userInfo.Length > 1 ? Uri.UnescapeDataString(userInfo[1]) : "",
            SslMode = SslMode.Require,
            Timeout = 15,
            CommandTimeout = 30,
            MaxPoolSize = 10,
            Pooling = true
        };

        var sslModeValue = uri.Query.TrimStart('?').Split('&', StringSplitOptions.RemoveEmptyEntries)
            .Select(part => part.Split('=', 2))
            .FirstOrDefault(part => part.Length == 2 && Uri.UnescapeDataString(part[0]) == "sslmode")?[1];
        if (Enum.TryParse<SslMode>(sslModeValue is null ? null : Uri.UnescapeDataString(sslModeValue), true, out var sslMode))
            builder.SslMode = sslMode;

        return builder.ConnectionString;
    }

    public async Task InitializeAsync()
    {
        await using var db = Connect(_connectionString);
        await db.OpenAsync();
        await using var command = db.CreateCommand();
        command.CommandText = """
            CREATE TABLE IF NOT EXISTS tasks (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                title VARCHAR(180) NOT NULL,
                notes TEXT NULL,
                category VARCHAR(32) NOT NULL DEFAULT 'Personal',
                priority VARCHAR(16) NOT NULL DEFAULT 'Medium',
                due_date DATE NULL,
                is_completed BOOLEAN NOT NULL DEFAULT FALSE,
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
            );
            CREATE INDEX IF NOT EXISTS ix_tasks_due_date ON tasks(due_date);
            CREATE INDEX IF NOT EXISTS ix_tasks_is_completed ON tasks(is_completed);
            CREATE TABLE IF NOT EXISTS data_protection_keys (
                id UUID PRIMARY KEY,
                xml TEXT NOT NULL
            );
            """;
        await command.ExecuteNonQueryAsync();
    }

    public async Task<List<TaskItem>> GetAllAsync()
    {
        var tasks = new List<TaskItem>();
        await using var db = Connect(_connectionString);
        await db.OpenAsync();
        await using var command = db.CreateCommand();
        command.CommandText = "SELECT id, title, notes, category, priority, due_date, is_completed, created_at FROM tasks ORDER BY is_completed, due_date NULLS LAST, created_at DESC";
        await using var reader = await command.ExecuteReaderAsync();
        while (await reader.ReadAsync())
        {
            tasks.Add(new TaskItem
            {
                Id = reader.GetInt64(0),
                Title = reader.GetString(1),
                Notes = reader.IsDBNull(2) ? null : reader.GetString(2),
                Category = reader.GetString(3),
                Priority = reader.GetString(4),
                DueDate = reader.IsDBNull(5) ? null : reader.GetFieldValue<DateOnly>(5).ToDateTime(TimeOnly.MinValue),
                IsCompleted = reader.GetBoolean(6),
                CreatedAt = reader.GetDateTime(7)
            });
        }
        return tasks;
    }

    public async Task AddAsync(string title, string? notes, string category, string priority, DateTime? dueDate)
    {
        await using var db = Connect(_connectionString);
        await db.OpenAsync();
        await using var command = db.CreateCommand();
        command.CommandText = "INSERT INTO tasks (title, notes, category, priority, due_date) VALUES (@title, @notes, @category, @priority, @dueDate)";
        command.Parameters.AddWithValue("title", title.Trim());
        command.Parameters.Add(new NpgsqlParameter("notes", NpgsqlDbType.Text) { Value = (object?)notes?.Trim() ?? DBNull.Value });
        command.Parameters.AddWithValue("category", NormalizeCategory(category));
        command.Parameters.AddWithValue("priority", NormalizePriority(priority));
        command.Parameters.Add(new NpgsqlParameter("dueDate", NpgsqlDbType.Date) { Value = dueDate is null ? DBNull.Value : DateOnly.FromDateTime(dueDate.Value) });
        await command.ExecuteNonQueryAsync();
    }

    public async Task UpdateAsync(long id, string title, string? notes, string category, string priority, DateTime? dueDate)
    {
        await using var db = Connect(_connectionString);
        await db.OpenAsync();
        await using var command = db.CreateCommand();
        command.CommandText = "UPDATE tasks SET title=@title, notes=@notes, category=@category, priority=@priority, due_date=@dueDate WHERE id=@id";
        command.Parameters.AddWithValue("title", title.Trim());
        command.Parameters.Add(new NpgsqlParameter("notes", NpgsqlDbType.Text) { Value = (object?)notes?.Trim() ?? DBNull.Value });
        command.Parameters.AddWithValue("category", NormalizeCategory(category));
        command.Parameters.AddWithValue("priority", NormalizePriority(priority));
        command.Parameters.Add(new NpgsqlParameter("dueDate", NpgsqlDbType.Date) { Value = dueDate is null ? DBNull.Value : DateOnly.FromDateTime(dueDate.Value) });
        command.Parameters.AddWithValue("id", id);
        await command.ExecuteNonQueryAsync();
    }

    public async Task ToggleAsync(long id)
    {
        await using var db = Connect(_connectionString);
        await db.OpenAsync();
        await using var command = db.CreateCommand();
        command.CommandText = "UPDATE tasks SET is_completed = NOT is_completed WHERE id=@id";
        command.Parameters.AddWithValue("id", id);
        await command.ExecuteNonQueryAsync();
    }

    public async Task DeleteAsync(long id)
    {
        await using var db = Connect(_connectionString);
        await db.OpenAsync();
        await using var command = db.CreateCommand();
        command.CommandText = "DELETE FROM tasks WHERE id=@id";
        command.Parameters.AddWithValue("id", id);
        await command.ExecuteNonQueryAsync();
    }

    private static string NormalizeCategory(string? category) => category is "Work" or "Personal" or "Learning" or "Health" ? category : "Personal";
    private static string NormalizePriority(string? priority) => priority is "Low" or "Medium" or "High" ? priority : "Medium";
}
